ridhozhr10/JCWDOL00806

- package-lock.json
- projects/server/migrations/20230302135343-create-users.js
- projects/server/migrations/20230306131401-create-tenant.js
- projects/server/src/index.js
fix autoIncrement
added DB Sync for sequelize
> fix autoIncrement in users and tenants tables

- projects/server/models/tenant.js
- projects/server/models/users.js
fix id datatypes for users and tenant model
> fix uuidv4 datatype

- projects/server/migrations/20230302135343-create-users.js
- projects/server/migrations/20230306131401-create-tenant.js
- projects/server/models/tenant.js
- projects/server/models/users.js
add provider column on users and tenants table
> Model migration revision

- package-lock.json
- projects/client/package.json
- projects/client/src/App.js
- projects/client/src/pages/EditUserDetail.js
- projects/client/src/pages/RegisterPage.js
- projects/client/src/pages/UserDetail.js
- projects/server/src/controllers/usersControllers.js
- projects/server/src/routes/usersRouters.js
installed lib, add some pages, bug fix older pages
> installed datepicker library, added placeholder pages

- projects/client/.env.development
- projects/client/src/App.js
- projects/client/src/pages/ChangeEmail.js
- projects/client/src/pages/EditUserDetail.js
- projects/client/src/pages/Login.js
- projects/client/src/pages/NewPassword.js
- projects/client/src/pages/PassportLogin.js
- projects/client/src/pages/RegisterPage.js
- projects/client/src/pages/ResetPassword.js
- projects/client/src/pages/UserDetail.js
- projects/client/src/pages/UserVerify.js
- projects/server/src/auth/passportFacebook.js
- projects/server/src/auth/passportGoogle.js
- projects/server/src/controllers/usersControllers.js
- projects/server/src/routes/authFacebookRouter.js
- projects/server/src/routes/authGoogleRouters.js
> bugfix, finished users profile page, finish change email feature

- projects/client/src/pages/Login.js
- projects/server/src/controllers/usersControllers.js
fixed login feature when user is using salted email
> fix login using salted email

- projects/client/src/App.js
- projects/client/src/pages/RoomSpecial.js
- projects/client/src/pages/RoomUnavailable.js
- projects/client/src/pages/TenantProperty.js
- projects/client/src/pages/tenantDashboard.js
- projects/client/src/pages/tenantLogin.js
- projects/server/src/controllers/roomController.js
- projects/server/src/routes/roomRouter.js
add feature add unavailable room and special price
> finishing feature add unavailable room and special price

- projects/client/src/pages/Login.js
- projects/client/src/pages/NewPassword.js
> bugfix reset password feature

- projects/client/src/App.js
- projects/client/src/components/TenantNavItem.js
- projects/client/src/components/TenantNavbar.js
- projects/client/src/index.css
- projects/client/src/pages/CalendarPage.js
- projects/client/src/pages/TenantOrders.js
- projects/client/src/pages/TenantProperty.js
- projects/client/src/pages/TenantPropertyRoomList.js
- projects/client/src/pages/TenantRoom.js
- projects/client/src/pages/tenantDashboard.js
- projects/server/migrations/20230302140151-create-order.js
- projects/server/models/order.js
- projects/server/src/controllers/roomController.js
- projects/server/src/controllers/tenantController.js
fix ERD, imported TenantNavbar component in tenant pages.
> add column 'notes' in order table, added tenant navbar in tenant pages

- projects/client/src/components/LoginModal.js
- projects/client/src/components/Navbar.js
- projects/client/src/components/RegisterModal.js
add modal for login and register on navbar
> fix navbar login and register

- projects/client/src/components/OrderCard.js
- projects/client/src/components/TenantNavbar.js
- projects/client/src/pages/RegisterPage.js
> fix register page

- projects/client/src/components/OrderCard.js
- projects/client/src/index.css
- projects/client/src/pages/TenantOrders.js
- projects/server/src/controllers/transactionController.js
- projects/server/src/routes/transactionRouter.js
Finishing feature #JFPG0-22 (view payment proof modal, see order detail modal)
> finish search invoice feature, add image and detail modal

- projects/client/src/components/CheckoutContent.js
- projects/client/src/components/Navbar.js
- projects/client/src/components/RoomCard.js
- projects/client/src/pages/Login.js
- projects/client/src/pages/PropertyDetail.js
- projects/client/src/pages/UserVerify.js
- get data check in and check out from property detail page to checkout page
- fix navbar
> complete feature/JFPG0-4 and fix navbar

- projects/client/src/components/CheckoutContent.js
- projects/client/src/components/Navbar.js
- projects/server/src/controllers/transactionController.js
- fix navbar
- after book, navigate to order list
> fix feature/JFPG0-4 and navbar

- projects/client/src/components/UserOrderCard.js
- projects/client/src/pages/UserOrders.js
- add upload payment proof button on order list
- add view payment proof on order list
> push feature/JFPG0-5 frontend

- projects/client/src/components/Navbar.js
- projects/client/src/components/UserOrderCard.js
- projects/client/src/pages/Login.js
- projects/client/src/pages/PropertyDetail.js
- projects/client/src/pages/RegisterPage.js
- projects/client/src/pages/UserChangePassword.js
- projects/client/src/pages/UserDetail.js
- projects/client/src/pages/UserOrders.js
- projects/client/src/pages/tenantLogin.js
- projects/client/src/pages/tenantRegister.js
- add navigate to profile, order list, and add onclick function for navbar sidebar
- add icon on user login page
- add file size validation for upload payment proof on user order card
- add navbar and footer on user register page
- fix get start and end date from params on property detail page
- add navbar and footer on user change password page, and navigate to user detail page after success change password
- add footer on user detail page, and add button to navigate to user change password
- fix navbar and footer on user order page
- add navbar and footer on tenant login page
- add navbar and footer on tenant register page
> fix on client side

- projects/client/src/components/CheckoutContent.js
- projects/server/src/controllers/transactionController.js
- fix double booking problem
- disable booking button if selected start date and end date between unavailable date
- send notif if room already booked by other user with same room id and selected date
- send notif if user booked on unavailable date with selected date from property detail page
> fix feature/booking

- projects/client/src/components/CheckoutContent.js
- projects/client/src/components/PropertyCard.js
- projects/client/src/components/RoomCard.js
- projects/client/src/components/UserOrderCard.js
- projects/client/src/pages/PropertyDetail.js
- projects/client/src/pages/TenantOrders.js
- projects/client/src/pages/TenantProperty.js
- projects/client/src/pages/UserDetail.js
- projects/server/src/index.js
> fix routing for image express static

- projects/client/src/components/OrderCard.js
- projects/client/src/pages/TenantOrders.js
- projects/server/config/config.js
- projects/server/src/controllers/transactionController.js
- added information for payment deadline on waiting for payment status
- changed book and reject trigger to "Expired" status and UPDATE notes column
- change timezone for sequelize to run at gmt+7
> show payment deadline for tenant order list

- projects/client/src/pages/RoomSpecial.js
- projects/server/src/controllers/roomController.js
- projects/server/src/routes/roomRouter.js
- add check for existing special price to prevent double entry
> added check for existing special price

- projects/server/src/routes/authFacebookRouter.js
> fix facebook login auth

- projects/client/src/components/PropertyCard.js
- projects/client/src/components/RoomCard.js
- projects/client/src/pages/Login.js
- projects/client/src/pages/PropertyDetail.js
- projects/server/src/controllers/transactionController.js
- projects/server/src/controllers/usersControllers.js
- fix rating on property detail
- change text from "per night" into "/ night"
- change email login form into email or phone number form
> fix rating and login
